// <auto-generated />
#if MACARON_FUNCTIONAL_UNITASK
#nullable enable

using System;
using System.Threading;
using Cysharp.Threading.Tasks;

namespace Macaron.Functional.UniTaskExtensions
{
    partial class Extensions
    {
        public static async UniTask<T> TapAsync<T>(
            this UniTask<T> self, Func<T, CancellationToken, UniTask> fnAsync, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T>(
            this UniTask<T> self, Action<T> action, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(result);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1>(
            this UniTask<T> self, Func<TArg1, T, CancellationToken, UniTask> fnAsync, TArg1 arg1, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(arg1, result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1>(
            this UniTask<T> self, Action<TArg1, T> action, TArg1 arg1, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(arg1, result);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2>(
            this UniTask<T> self, Func<TArg1, TArg2, T, CancellationToken, UniTask> fnAsync, TArg1 arg1, TArg2 arg2, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(arg1, arg2, result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2>(
            this UniTask<T> self, Action<TArg1, TArg2, T> action, TArg1 arg1, TArg2 arg2, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(arg1, arg2, result);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3>(
            this UniTask<T> self, Func<TArg1, TArg2, TArg3, T, CancellationToken, UniTask> fnAsync, TArg1 arg1, TArg2 arg2, TArg3 arg3, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(arg1, arg2, arg3, result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3>(
            this UniTask<T> self, Action<TArg1, TArg2, TArg3, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(arg1, arg2, arg3, result);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4>(
            this UniTask<T> self, Func<TArg1, TArg2, TArg3, TArg4, T, CancellationToken, UniTask> fnAsync, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(arg1, arg2, arg3, arg4, result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4>(
            this UniTask<T> self, Action<TArg1, TArg2, TArg3, TArg4, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(arg1, arg2, arg3, arg4, result);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
            this UniTask<T> self, Func<TArg1, TArg2, TArg3, TArg4, TArg5, T, CancellationToken, UniTask> fnAsync, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(arg1, arg2, arg3, arg4, arg5, result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
            this UniTask<T> self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(arg1, arg2, arg3, arg4, arg5, result);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
            this UniTask<T> self, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T, CancellationToken, UniTask> fnAsync, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(arg1, arg2, arg3, arg4, arg5, arg6, result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
            this UniTask<T> self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(arg1, arg2, arg3, arg4, arg5, arg6, result);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
            this UniTask<T> self, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T, CancellationToken, UniTask> fnAsync, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            await fnAsync(arg1, arg2, arg3, arg4, arg5, arg6, arg7, result, cancellationToken);

            return result;
        }

        public static async UniTask<T> TapAsync<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
            this UniTask<T> self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, CancellationToken cancellationToken
        ) where T : notnull
        {
            cancellationToken.ThrowIfCancellationRequested();

            var result = await self.AttachExternalCancellation(cancellationToken);

            action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, result);

            return result;
        }

    }
}
#endif
