// <auto-generated />
using System.Runtime.CompilerServices;

namespace Macaron.Functional;

partial class EitherExtensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1>(
        this Either<TLeft, TRight> either, TArg1 arg1, Action<TRight, TArg1> action
    )
    {
        return either.Tap(right => action(right, arg1));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, Action<TRight, TArg1, TArg2> action
    )
    {
        return either.Tap(right => action(right, arg1, arg2));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, Action<TRight, TArg1, TArg2, TArg3> action
    )
    {
        return either.Tap(right => action(right, arg1, arg2, arg3));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, Action<TRight, TArg1, TArg2, TArg3, TArg4> action
    )
    {
        return either.Tap(right => action(right, arg1, arg2, arg3, arg4));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, Action<TRight, TArg1, TArg2, TArg3, TArg4, TArg5> action
    )
    {
        return either.Tap(right => action(right, arg1, arg2, arg3, arg4, arg5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, Action<TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action
    )
    {
        return either.Tap(right => action(right, arg1, arg2, arg3, arg4, arg5, arg6));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, Action<TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action
    )
    {
        return either.Tap(right => action(right, arg1, arg2, arg3, arg4, arg5, arg6, arg7));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1>(
        this Either<TLeft, TRight> either, Action<TArg1, TRight> action, TArg1 arg1
    )
    {
        return either.Tap(right => action(arg1, right));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TRight> action, TArg1 arg1, TArg2 arg2
    )
    {
        return either.Tap(right => action(arg1, arg2, right));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TRight> action, TArg1 arg1, TArg2 arg2, TArg3 arg3
    )
    {
        return either.Tap(right => action(arg1, arg2, arg3, right));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TRight> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4
    )
    {
        return either.Tap(right => action(arg1, arg2, arg3, arg4, right));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TRight> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5
    )
    {
        return either.Tap(right => action(arg1, arg2, arg3, arg4, arg5, right));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TRight> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6
    )
    {
        return either.Tap(right => action(arg1, arg2, arg3, arg4, arg5, arg6, right));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> Tap<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TRight> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7
    )
    {
        return either.Tap(right => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, right));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1>(
        this Either<TLeft, TRight> either, TArg1 arg1, Action<TLeft, TArg1> action
    )
    {
        return either.TapLeft(left => action(left, arg1));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, Action<TLeft, TArg1, TArg2> action
    )
    {
        return either.TapLeft(left => action(left, arg1, arg2));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, Action<TLeft, TArg1, TArg2, TArg3> action
    )
    {
        return either.TapLeft(left => action(left, arg1, arg2, arg3));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, Action<TLeft, TArg1, TArg2, TArg3, TArg4> action
    )
    {
        return either.TapLeft(left => action(left, arg1, arg2, arg3, arg4));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, Action<TLeft, TArg1, TArg2, TArg3, TArg4, TArg5> action
    )
    {
        return either.TapLeft(left => action(left, arg1, arg2, arg3, arg4, arg5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, Action<TLeft, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action
    )
    {
        return either.TapLeft(left => action(left, arg1, arg2, arg3, arg4, arg5, arg6));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Either<TLeft, TRight> either, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, Action<TLeft, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action
    )
    {
        return either.TapLeft(left => action(left, arg1, arg2, arg3, arg4, arg5, arg6, arg7));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1>(
        this Either<TLeft, TRight> either, Action<TArg1, TLeft> action, TArg1 arg1
    )
    {
        return either.TapLeft(left => action(arg1, left));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TLeft> action, TArg1 arg1, TArg2 arg2
    )
    {
        return either.TapLeft(left => action(arg1, arg2, left));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TLeft> action, TArg1 arg1, TArg2 arg2, TArg3 arg3
    )
    {
        return either.TapLeft(left => action(arg1, arg2, arg3, left));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TLeft> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4
    )
    {
        return either.TapLeft(left => action(arg1, arg2, arg3, arg4, left));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TLeft> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5
    )
    {
        return either.TapLeft(left => action(arg1, arg2, arg3, arg4, arg5, left));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TLeft> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6
    )
    {
        return either.TapLeft(left => action(arg1, arg2, arg3, arg4, arg5, arg6, left));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Either<TLeft, TRight> TapLeft<TLeft, TRight, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Either<TLeft, TRight> either, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TLeft> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7
    )
    {
        return either.TapLeft(left => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, left));
    }

}
