// <auto-generated />
namespace Macaron.Functional;

partial class Extensions
{
    public static T Also<T>(
        this T self, Action<T> action
    ) where T : notnull
    {
        action(self);
        return self;
    }

    public static T Also<T, TArg1>(
        this T self, Action<T, TArg1> action, TArg1 arg1
    ) where T : notnull
    {
        action(self, arg1);
        return self;
    }

    public static T Also<T, TArg1, TArg2>(
        this T self, Action<T, TArg1, TArg2> action, TArg1 arg1, TArg2 arg2
    ) where T : notnull
    {
        action(self, arg1, arg2);
        return self;
    }

    public static T Also<T, TArg1, TArg2, TArg3>(
        this T self, Action<T, TArg1, TArg2, TArg3> action, TArg1 arg1, TArg2 arg2, TArg3 arg3
    ) where T : notnull
    {
        action(self, arg1, arg2, arg3);
        return self;
    }

    public static T Also<T, TArg1, TArg2, TArg3, TArg4>(
        this T self, Action<T, TArg1, TArg2, TArg3, TArg4> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4
    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4);
        return self;
    }

    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this T self, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5
    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4, arg5);
        return self;
    }

    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this T self, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6
    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4, arg5, arg6);
        return self;
    }

    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this T self, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7
    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        return self;
    }

}
