// <auto-generated />
using System.Runtime.CompilerServices;

namespace Macaron.Functional;

partial class Extensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4) Concat<T1, T2, T3, T4>(this (T1, T2) first, (T3, T4) second)
    {
        return (first.Item1, first.Item2, second.Item1, second.Item2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5) Concat<T1, T2, T3, T4, T5>(this (T1, T2) first, (T3, T4, T5) second)
    {
        return (first.Item1, first.Item2, second.Item1, second.Item2, second.Item3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6) Concat<T1, T2, T3, T4, T5, T6>(this (T1, T2) first, (T3, T4, T5, T6) second)
    {
        return (first.Item1, first.Item2, second.Item1, second.Item2, second.Item3, second.Item4);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7) Concat<T1, T2, T3, T4, T5, T6, T7>(this (T1, T2) first, (T3, T4, T5, T6, T7) second)
    {
        return (first.Item1, first.Item2, second.Item1, second.Item2, second.Item3, second.Item4, second.Item5);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Concat<T1, T2, T3, T4, T5, T6, T7, T8>(this (T1, T2) first, (T3, T4, T5, T6, T7, T8) second)
    {
        return (first.Item1, first.Item2, second.Item1, second.Item2, second.Item3, second.Item4, second.Item5, second.Item6);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5) Concat<T1, T2, T3, T4, T5>(this (T1, T2, T3) first, (T4, T5) second)
    {
        return (first.Item1, first.Item2, first.Item3, second.Item1, second.Item2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6) Concat<T1, T2, T3, T4, T5, T6>(this (T1, T2, T3) first, (T4, T5, T6) second)
    {
        return (first.Item1, first.Item2, first.Item3, second.Item1, second.Item2, second.Item3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7) Concat<T1, T2, T3, T4, T5, T6, T7>(this (T1, T2, T3) first, (T4, T5, T6, T7) second)
    {
        return (first.Item1, first.Item2, first.Item3, second.Item1, second.Item2, second.Item3, second.Item4);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Concat<T1, T2, T3, T4, T5, T6, T7, T8>(this (T1, T2, T3) first, (T4, T5, T6, T7, T8) second)
    {
        return (first.Item1, first.Item2, first.Item3, second.Item1, second.Item2, second.Item3, second.Item4, second.Item5);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6) Concat<T1, T2, T3, T4, T5, T6>(this (T1, T2, T3, T4) first, (T5, T6) second)
    {
        return (first.Item1, first.Item2, first.Item3, first.Item4, second.Item1, second.Item2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7) Concat<T1, T2, T3, T4, T5, T6, T7>(this (T1, T2, T3, T4) first, (T5, T6, T7) second)
    {
        return (first.Item1, first.Item2, first.Item3, first.Item4, second.Item1, second.Item2, second.Item3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Concat<T1, T2, T3, T4, T5, T6, T7, T8>(this (T1, T2, T3, T4) first, (T5, T6, T7, T8) second)
    {
        return (first.Item1, first.Item2, first.Item3, first.Item4, second.Item1, second.Item2, second.Item3, second.Item4);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7) Concat<T1, T2, T3, T4, T5, T6, T7>(this (T1, T2, T3, T4, T5) first, (T6, T7) second)
    {
        return (first.Item1, first.Item2, first.Item3, first.Item4, first.Item5, second.Item1, second.Item2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Concat<T1, T2, T3, T4, T5, T6, T7, T8>(this (T1, T2, T3, T4, T5) first, (T6, T7, T8) second)
    {
        return (first.Item1, first.Item2, first.Item3, first.Item4, first.Item5, second.Item1, second.Item2, second.Item3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Concat<T1, T2, T3, T4, T5, T6, T7, T8>(this (T1, T2, T3, T4, T5, T6) first, (T7, T8) second)
    {
        return (first.Item1, first.Item2, first.Item3, first.Item4, first.Item5, first.Item6, second.Item1, second.Item2);
    }

}

