// <auto-generated />
namespace Macaron.Functional;

partial class Extensions
{
    public static Action Bind<T1>(
        this Action<T1> action, T1 arg1
    )
    {
        return () => action(arg1);
    }

    public static Func<TResult> Bind<T1, TResult>(
        this Func<T1, TResult> fn, T1 arg1
    )
    {
        return () => fn(arg1);
    }

    public static Action Bind<T1, T2>(
        this Action<T1, T2> action, T1 arg1, T2 arg2
    )
    {
        return () => action(arg1, arg2);
    }

    public static Func<TResult> Bind<T1, T2, TResult>(
        this Func<T1, T2, TResult> fn, T1 arg1, T2 arg2
    )
    {
        return () => fn(arg1, arg2);
    }

    public static Action Bind<T1, T2, T3>(
        this Action<T1, T2, T3> action, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return () => action(arg1, arg2, arg3);
    }

    public static Func<TResult> Bind<T1, T2, T3, TResult>(
        this Func<T1, T2, T3, TResult> fn, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return () => fn(arg1, arg2, arg3);
    }

    public static Action Bind<T1, T2, T3, T4>(
        this Action<T1, T2, T3, T4> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return () => action(arg1, arg2, arg3, arg4);
    }

    public static Func<TResult> Bind<T1, T2, T3, T4, TResult>(
        this Func<T1, T2, T3, T4, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return () => fn(arg1, arg2, arg3, arg4);
    }

    public static Action Bind<T1, T2, T3, T4, T5>(
        this Action<T1, T2, T3, T4, T5> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return () => action(arg1, arg2, arg3, arg4, arg5);
    }

    public static Func<TResult> Bind<T1, T2, T3, T4, T5, TResult>(
        this Func<T1, T2, T3, T4, T5, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return () => fn(arg1, arg2, arg3, arg4, arg5);
    }

    public static Action Bind<T1, T2, T3, T4, T5, T6>(
        this Action<T1, T2, T3, T4, T5, T6> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6
    )
    {
        return () => action(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Func<TResult> Bind<T1, T2, T3, T4, T5, T6, TResult>(
        this Func<T1, T2, T3, T4, T5, T6, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6
    )
    {
        return () => fn(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Action Bind<T1, T2, T3, T4, T5, T6, T7>(
        this Action<T1, T2, T3, T4, T5, T6, T7> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7
    )
    {
        return () => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<TResult> Bind<T1, T2, T3, T4, T5, T6, T7, TResult>(
        this Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7
    )
    {
        return () => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Action Bind<T1, T2, T3, T4, T5, T6, T7, T8>(
        this Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8
    )
    {
        return () => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<TResult> Bind<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        this Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8
    )
    {
        return () => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

}
