// <auto-generated />
namespace Macaron.Functional;

partial class Extensions
{
    public static T Tap<T>(
        this T self, Action<T> action
    ) where T : notnull
    {
        action(self);
        return self;
    }

    public static T Tap<T, TArg1>(
        this T self, Action<TArg1, T> action, TArg1 arg1
    ) where T : notnull
    {
        action(arg1, self);
        return self;
    }

    public static T Tap<T, TArg1, TArg2>(
        this T self, Action<TArg1, TArg2, T> action, TArg1 arg1, TArg2 arg2
    ) where T : notnull
    {
        action(arg1, arg2, self);
        return self;
    }

    public static T Tap<T, TArg1, TArg2, TArg3>(
        this T self, Action<TArg1, TArg2, TArg3, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3
    ) where T : notnull
    {
        action(arg1, arg2, arg3, self);
        return self;
    }

    public static T Tap<T, TArg1, TArg2, TArg3, TArg4>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, self);
        return self;
    }

    public static T Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, arg5, self);
        return self;
    }

    public static T Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, arg5, arg6, self);
        return self;
    }

    public static T Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, self);
        return self;
    }

    public static T Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, TArg8 arg8
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, self);
        return self;
    }

}
