// <auto-generated />
using System.Runtime.CompilerServices;

namespace Macaron.Functional;

partial class Extensions
{
    public static T Also<T>(
        this T self, Action<T> action
    ) where T : notnull
    {
        action(self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1>(
        this T self, TArg1 arg1, Action<T, TArg1> action

    ) where T : notnull
    {
        action(self, arg1);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2>(
        this T self, TArg1 arg1, TArg2 arg2, Action<T, TArg1, TArg2> action

    ) where T : notnull
    {
        action(self, arg1, arg2);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3>(
        this T self, TArg1 arg1, TArg2 arg2, TArg3 arg3, Action<T, TArg1, TArg2, TArg3> action

    ) where T : notnull
    {
        action(self, arg1, arg2, arg3);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4>(
        this T self, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, Action<T, TArg1, TArg2, TArg3, TArg4> action

    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this T self, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5> action

    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4, arg5);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this T self, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action

    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4, arg5, arg6);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this T self, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action

    ) where T : notnull
    {
        action(self, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1>(
        this T self, Action<TArg1, T> action, TArg1 arg1
    ) where T : notnull
    {
        action(arg1, self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2>(
        this T self, Action<TArg1, TArg2, T> action, TArg1 arg1, TArg2 arg2
    ) where T : notnull
    {
        action(arg1, arg2, self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3>(
        this T self, Action<TArg1, TArg2, TArg3, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3
    ) where T : notnull
    {
        action(arg1, arg2, arg3, self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, arg5, self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, arg5, arg6, self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static T Also<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this T self, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7
    ) where T : notnull
    {
        action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, self);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2) Also<T1, T2>(
        this (T1, T2) self, Action<T1, T2> action

    )
    {
        action(self.Item1, self.Item2);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3) Also<T1, T2, T3>(
        this (T1, T2, T3) self, Action<T1, T2, T3> action

    )
    {
        action(self.Item1, self.Item2, self.Item3);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4) Also<T1, T2, T3, T4>(
        this (T1, T2, T3, T4) self, Action<T1, T2, T3, T4> action

    )
    {
        action(self.Item1, self.Item2, self.Item3, self.Item4);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5) Also<T1, T2, T3, T4, T5>(
        this (T1, T2, T3, T4, T5) self, Action<T1, T2, T3, T4, T5> action

    )
    {
        action(self.Item1, self.Item2, self.Item3, self.Item4, self.Item5);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6) Also<T1, T2, T3, T4, T5, T6>(
        this (T1, T2, T3, T4, T5, T6) self, Action<T1, T2, T3, T4, T5, T6> action

    )
    {
        action(self.Item1, self.Item2, self.Item3, self.Item4, self.Item5, self.Item6);
        return self;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7) Also<T1, T2, T3, T4, T5, T6, T7>(
        this (T1, T2, T3, T4, T5, T6, T7) self, Action<T1, T2, T3, T4, T5, T6, T7> action

    )
    {
        action(self.Item1, self.Item2, self.Item3, self.Item4, self.Item5, self.Item6, self.Item7);
        return self;
    }

}
