// <auto-generated />
using System.Runtime.CompilerServices;

namespace Macaron.Functional;

partial class MaybeExtensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1>(
        this Maybe<T> maybe, TArg1 arg1, Action<T, TArg1> action
    )
    {
        return maybe.Tap(value => action(value, arg1));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, Action<T, TArg1, TArg2> action
    )
    {
        return maybe.Tap(value => action(value, arg1, arg2));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, Action<T, TArg1, TArg2, TArg3> action
    )
    {
        return maybe.Tap(value => action(value, arg1, arg2, arg3));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, Action<T, TArg1, TArg2, TArg3, TArg4> action
    )
    {
        return maybe.Tap(value => action(value, arg1, arg2, arg3, arg4));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5> action
    )
    {
        return maybe.Tap(value => action(value, arg1, arg2, arg3, arg4, arg5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action
    )
    {
        return maybe.Tap(value => action(value, arg1, arg2, arg3, arg4, arg5, arg6));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, Action<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action
    )
    {
        return maybe.Tap(value => action(value, arg1, arg2, arg3, arg4, arg5, arg6, arg7));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1>(
        this Maybe<T> maybe, Action<TArg1, T> action, TArg1 arg1
    )
    {
        return maybe.Tap(value => action(arg1, value));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2>(
        this Maybe<T> maybe, Action<TArg1, TArg2, T> action, TArg1 arg1, TArg2 arg2
    )
    {
        return maybe.Tap(value => action(arg1, arg2, value));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3
    )
    {
        return maybe.Tap(value => action(arg1, arg2, arg3, value));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4
    )
    {
        return maybe.Tap(value => action(arg1, arg2, arg3, arg4, value));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4, TArg5, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5
    )
    {
        return maybe.Tap(value => action(arg1, arg2, arg3, arg4, arg5, value));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6
    )
    {
        return maybe.Tap(value => action(arg1, arg2, arg3, arg4, arg5, arg6, value));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> Tap<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, T> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7
    )
    {
        return maybe.Tap(value => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, value));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1>(
        this Maybe<T> maybe, TArg1 arg1, Action<TArg1> action
    )
    {
        return maybe.TapNothing(() => action(arg1));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, Action<TArg1, TArg2> action
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, Action<TArg1, TArg2, TArg3> action
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, Action<TArg1, TArg2, TArg3, TArg4> action
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, Action<TArg1, TArg2, TArg3, TArg4, TArg5> action
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4, arg5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4, arg5, arg6));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Maybe<T> maybe, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1>(
        this Maybe<T> maybe, Action<TArg1> action, TArg1 arg1
    )
    {
        return maybe.TapNothing(() => action(arg1));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2>(
        this Maybe<T> maybe, Action<TArg1, TArg2> action, TArg1 arg1, TArg2 arg2
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3> action, TArg1 arg1, TArg2 arg2, TArg3 arg3
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4, TArg5>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4, TArg5> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4, arg5));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4, arg5, arg6));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Maybe<T> TapNothing<T, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(
        this Maybe<T> maybe, Action<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> action, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4, TArg5 arg5, TArg6 arg6, TArg7 arg7
    )
    {
        return maybe.TapNothing(() => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7));
    }

}
