// <auto-generated />
using System.Runtime.CompilerServices;

namespace Macaron.Functional;

partial class Utility
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2) Tuple<T1, T2>(
        T1 value1,
        T2 value2
    )
    {
        return (
            value1,
            value2
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3) Tuple<T1, T2, T3>(
        T1 value1,
        T2 value2,
        T3 value3
    )
    {
        return (
            value1,
            value2,
            value3
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4) Tuple<T1, T2, T3, T4>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4
    )
    {
        return (
            value1,
            value2,
            value3,
            value4
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5) Tuple<T1, T2, T3, T4, T5>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5
    )
    {
        return (
            value1,
            value2,
            value3,
            value4,
            value5
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6) Tuple<T1, T2, T3, T4, T5, T6>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6
    )
    {
        return (
            value1,
            value2,
            value3,
            value4,
            value5,
            value6
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7) Tuple<T1, T2, T3, T4, T5, T6, T7>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7
    )
    {
        return (
            value1,
            value2,
            value3,
            value4,
            value5,
            value6,
            value7
        );
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static (T1, T2, T3, T4, T5, T6, T7, T8) Tuple<T1, T2, T3, T4, T5, T6, T7, T8>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7,
        T8 value8
    )
    {
        return (
            value1,
            value2,
            value3,
            value4,
            value5,
            value6,
            value7,
            value8
        );
    }

}