// <auto-generated />
namespace Macaron.Functional;

partial class Utility
{
    public static Func<T1, Func<T2, TResult>> Curry<T1, T2, TResult>(
        Func<T1, T2, TResult> fn
    )
    {
        return arg1 => arg2 => fn(arg1, arg2);
    }

    public static Func<T1, Action<T2>> Curry<T1, T2>(
        Action<T1, T2> action
    )
    {
        return arg1 => arg2 => action(arg1, arg2);
    }
    public static Func<T2, TResult> Curry<T1, T2, TResult>(
        Func<T1, T2, TResult> fn, T1 arg1
    )
    {
        return arg2 => fn(arg1, arg2);
    }

    public static Action<T2> Curry<T1, T2>(
        Action<T1, T2> action, T1 arg1
    )
    {
        return arg2 => action(arg1, arg2);
    }
    public static Func<T1, Func<T2, Func<T3, TResult>>> Curry<T1, T2, T3, TResult>(
        Func<T1, T2, T3, TResult> fn
    )
    {
        return arg1 => arg2 => arg3 => fn(arg1, arg2, arg3);
    }

    public static Func<T1, Func<T2, Action<T3>>> Curry<T1, T2, T3>(
        Action<T1, T2, T3> action
    )
    {
        return arg1 => arg2 => arg3 => action(arg1, arg2, arg3);
    }
    public static Func<T2, Func<T3, TResult>> Curry<T1, T2, T3, TResult>(
        Func<T1, T2, T3, TResult> fn, T1 arg1
    )
    {
        return arg2 => arg3 => fn(arg1, arg2, arg3);
    }

    public static Func<T2, Action<T3>> Curry<T1, T2, T3>(
        Action<T1, T2, T3> action, T1 arg1
    )
    {
        return arg2 => arg3 => action(arg1, arg2, arg3);
    }
    public static Func<T3, TResult> Curry<T1, T2, T3, TResult>(
        Func<T1, T2, T3, TResult> fn, T1 arg1, T2 arg2
    )
    {
        return arg3 => fn(arg1, arg2, arg3);
    }

    public static Action<T3> Curry<T1, T2, T3>(
        Action<T1, T2, T3> action, T1 arg1, T2 arg2
    )
    {
        return arg3 => action(arg1, arg2, arg3);
    }
    public static Func<T1, Func<T2, Func<T3, Func<T4, TResult>>>> Curry<T1, T2, T3, T4, TResult>(
        Func<T1, T2, T3, T4, TResult> fn
    )
    {
        return arg1 => arg2 => arg3 => arg4 => fn(arg1, arg2, arg3, arg4);
    }

    public static Func<T1, Func<T2, Func<T3, Action<T4>>>> Curry<T1, T2, T3, T4>(
        Action<T1, T2, T3, T4> action
    )
    {
        return arg1 => arg2 => arg3 => arg4 => action(arg1, arg2, arg3, arg4);
    }
    public static Func<T2, Func<T3, Func<T4, TResult>>> Curry<T1, T2, T3, T4, TResult>(
        Func<T1, T2, T3, T4, TResult> fn, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => fn(arg1, arg2, arg3, arg4);
    }

    public static Func<T2, Func<T3, Action<T4>>> Curry<T1, T2, T3, T4>(
        Action<T1, T2, T3, T4> action, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => action(arg1, arg2, arg3, arg4);
    }
    public static Func<T3, Func<T4, TResult>> Curry<T1, T2, T3, T4, TResult>(
        Func<T1, T2, T3, T4, TResult> fn, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => fn(arg1, arg2, arg3, arg4);
    }

    public static Func<T3, Action<T4>> Curry<T1, T2, T3, T4>(
        Action<T1, T2, T3, T4> action, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => action(arg1, arg2, arg3, arg4);
    }
    public static Func<T4, TResult> Curry<T1, T2, T3, T4, TResult>(
        Func<T1, T2, T3, T4, TResult> fn, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => fn(arg1, arg2, arg3, arg4);
    }

    public static Action<T4> Curry<T1, T2, T3, T4>(
        Action<T1, T2, T3, T4> action, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => action(arg1, arg2, arg3, arg4);
    }
    public static Func<T1, Func<T2, Func<T3, Func<T4, Func<T5, TResult>>>>> Curry<T1, T2, T3, T4, T5, TResult>(
        Func<T1, T2, T3, T4, T5, TResult> fn
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => fn(arg1, arg2, arg3, arg4, arg5);
    }

    public static Func<T1, Func<T2, Func<T3, Func<T4, Action<T5>>>>> Curry<T1, T2, T3, T4, T5>(
        Action<T1, T2, T3, T4, T5> action
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => action(arg1, arg2, arg3, arg4, arg5);
    }
    public static Func<T2, Func<T3, Func<T4, Func<T5, TResult>>>> Curry<T1, T2, T3, T4, T5, TResult>(
        Func<T1, T2, T3, T4, T5, TResult> fn, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => fn(arg1, arg2, arg3, arg4, arg5);
    }

    public static Func<T2, Func<T3, Func<T4, Action<T5>>>> Curry<T1, T2, T3, T4, T5>(
        Action<T1, T2, T3, T4, T5> action, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => action(arg1, arg2, arg3, arg4, arg5);
    }
    public static Func<T3, Func<T4, Func<T5, TResult>>> Curry<T1, T2, T3, T4, T5, TResult>(
        Func<T1, T2, T3, T4, T5, TResult> fn, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => fn(arg1, arg2, arg3, arg4, arg5);
    }

    public static Func<T3, Func<T4, Action<T5>>> Curry<T1, T2, T3, T4, T5>(
        Action<T1, T2, T3, T4, T5> action, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => action(arg1, arg2, arg3, arg4, arg5);
    }
    public static Func<T4, Func<T5, TResult>> Curry<T1, T2, T3, T4, T5, TResult>(
        Func<T1, T2, T3, T4, T5, TResult> fn, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => fn(arg1, arg2, arg3, arg4, arg5);
    }

    public static Func<T4, Action<T5>> Curry<T1, T2, T3, T4, T5>(
        Action<T1, T2, T3, T4, T5> action, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => action(arg1, arg2, arg3, arg4, arg5);
    }
    public static Func<T5, TResult> Curry<T1, T2, T3, T4, T5, TResult>(
        Func<T1, T2, T3, T4, T5, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => fn(arg1, arg2, arg3, arg4, arg5);
    }

    public static Action<T5> Curry<T1, T2, T3, T4, T5>(
        Action<T1, T2, T3, T4, T5> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => action(arg1, arg2, arg3, arg4, arg5);
    }
    public static Func<T1, Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, TResult>>>>>> Curry<T1, T2, T3, T4, T5, T6, TResult>(
        Func<T1, T2, T3, T4, T5, T6, TResult> fn
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => arg6 => fn(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Func<T1, Func<T2, Func<T3, Func<T4, Func<T5, Action<T6>>>>>> Curry<T1, T2, T3, T4, T5, T6>(
        Action<T1, T2, T3, T4, T5, T6> action
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => arg6 => action(arg1, arg2, arg3, arg4, arg5, arg6);
    }
    public static Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, TResult>>>>> Curry<T1, T2, T3, T4, T5, T6, TResult>(
        Func<T1, T2, T3, T4, T5, T6, TResult> fn, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => arg6 => fn(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Func<T2, Func<T3, Func<T4, Func<T5, Action<T6>>>>> Curry<T1, T2, T3, T4, T5, T6>(
        Action<T1, T2, T3, T4, T5, T6> action, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => arg6 => action(arg1, arg2, arg3, arg4, arg5, arg6);
    }
    public static Func<T3, Func<T4, Func<T5, Func<T6, TResult>>>> Curry<T1, T2, T3, T4, T5, T6, TResult>(
        Func<T1, T2, T3, T4, T5, T6, TResult> fn, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => arg6 => fn(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Func<T3, Func<T4, Func<T5, Action<T6>>>> Curry<T1, T2, T3, T4, T5, T6>(
        Action<T1, T2, T3, T4, T5, T6> action, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => arg6 => action(arg1, arg2, arg3, arg4, arg5, arg6);
    }
    public static Func<T4, Func<T5, Func<T6, TResult>>> Curry<T1, T2, T3, T4, T5, T6, TResult>(
        Func<T1, T2, T3, T4, T5, T6, TResult> fn, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => arg6 => fn(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Func<T4, Func<T5, Action<T6>>> Curry<T1, T2, T3, T4, T5, T6>(
        Action<T1, T2, T3, T4, T5, T6> action, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => arg6 => action(arg1, arg2, arg3, arg4, arg5, arg6);
    }
    public static Func<T5, Func<T6, TResult>> Curry<T1, T2, T3, T4, T5, T6, TResult>(
        Func<T1, T2, T3, T4, T5, T6, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => arg6 => fn(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Func<T5, Action<T6>> Curry<T1, T2, T3, T4, T5, T6>(
        Action<T1, T2, T3, T4, T5, T6> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => arg6 => action(arg1, arg2, arg3, arg4, arg5, arg6);
    }
    public static Func<T6, TResult> Curry<T1, T2, T3, T4, T5, T6, TResult>(
        Func<T1, T2, T3, T4, T5, T6, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return arg6 => fn(arg1, arg2, arg3, arg4, arg5, arg6);
    }

    public static Action<T6> Curry<T1, T2, T3, T4, T5, T6>(
        Action<T1, T2, T3, T4, T5, T6> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return arg6 => action(arg1, arg2, arg3, arg4, arg5, arg6);
    }
    public static Func<T1, Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, TResult>>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<T1, Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Action<T7>>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
    public static Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, TResult>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Action<T7>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
    public static Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, TResult>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => arg6 => arg7 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<T3, Func<T4, Func<T5, Func<T6, Action<T7>>>>> Curry<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => arg6 => arg7 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
    public static Func<T4, Func<T5, Func<T6, Func<T7, TResult>>>> Curry<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => arg6 => arg7 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<T4, Func<T5, Func<T6, Action<T7>>>> Curry<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => arg6 => arg7 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
    public static Func<T5, Func<T6, Func<T7, TResult>>> Curry<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => arg6 => arg7 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<T5, Func<T6, Action<T7>>> Curry<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => arg6 => arg7 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
    public static Func<T6, Func<T7, TResult>> Curry<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return arg6 => arg7 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<T6, Action<T7>> Curry<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return arg6 => arg7 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
    public static Func<T7, TResult> Curry<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6
    )
    {
        return arg7 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }

    public static Action<T7> Curry<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6
    )
    {
        return arg7 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
    public static Func<T1, Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, Func<T8, TResult>>>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T1, Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, Action<T8>>>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action
    )
    {
        return arg1 => arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
    public static Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, Func<T8, TResult>>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T2, Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, Action<T8>>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1
    )
    {
        return arg2 => arg3 => arg4 => arg5 => arg6 => arg7 => arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
    public static Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, Func<T8, TResult>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => arg6 => arg7 => arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T3, Func<T4, Func<T5, Func<T6, Func<T7, Action<T8>>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1, T2 arg2
    )
    {
        return arg3 => arg4 => arg5 => arg6 => arg7 => arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
    public static Func<T4, Func<T5, Func<T6, Func<T7, Func<T8, TResult>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => arg6 => arg7 => arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T4, Func<T5, Func<T6, Func<T7, Action<T8>>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1, T2 arg2, T3 arg3
    )
    {
        return arg4 => arg5 => arg6 => arg7 => arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
    public static Func<T5, Func<T6, Func<T7, Func<T8, TResult>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => arg6 => arg7 => arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T5, Func<T6, Func<T7, Action<T8>>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4
    )
    {
        return arg5 => arg6 => arg7 => arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
    public static Func<T6, Func<T7, Func<T8, TResult>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return arg6 => arg7 => arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T6, Func<T7, Action<T8>>> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5
    )
    {
        return arg6 => arg7 => arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
    public static Func<T7, Func<T8, TResult>> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6
    )
    {
        return arg7 => arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T7, Action<T8>> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6
    )
    {
        return arg7 => arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
    public static Func<T8, TResult> Curry<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7
    )
    {
        return arg8 => fn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Action<T8> Curry<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7
    )
    {
        return arg8 => action(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
    }
}
