// <auto-generated />
namespace Macaron.Functional;

partial class Utility
{
    public static void Nothing()
    {
    }

    public static void Nothing<T>(T value)
    {
    }

    public static void Nothing<T1, T2>(
        T1 value1,
        T2 value2
    )
    {
    }

    public static void Nothing<T1, T2, T3>(
        T1 value1,
        T2 value2,
        T3 value3
    )
    {
    }

    public static void Nothing<T1, T2, T3, T4>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4
    )
    {
    }

    public static void Nothing<T1, T2, T3, T4, T5>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5
    )
    {
    }

    public static void Nothing<T1, T2, T3, T4, T5, T6>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6
    )
    {
    }

    public static void Nothing<T1, T2, T3, T4, T5, T6, T7>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7
    )
    {
    }

    public static void Nothing<T1, T2, T3, T4, T5, T6, T7, T8>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7,
        T8 value8
    )
    {
    }

}