// <auto-generated />
using System.Runtime.CompilerServices;

namespace Macaron.Functional;

partial class Utility
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run(Action action)
    {
        action();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<TResult>(Func<TResult> fn)
    {
        return fn();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T>(T value, Action<T> action)
    {
        action(value);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T, TResult>(T value, Func<T, TResult> fn)
    {
        return fn(value);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2>(
        T1 value1,
        T2 value2,
        Action<T1, T2> action
    )
    {
        action(value1, value2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3>(
        T1 value1,
        T2 value2,
        T3 value3,
        Action<T1, T2, T3> action
    )
    {
        action(value1, value2, value3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        Action<T1, T2, T3, T4> action
    )
    {
        action(value1, value2, value3, value4);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        Action<T1, T2, T3, T4, T5> action
    )
    {
        action(value1, value2, value3, value4, value5);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5, T6>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        Action<T1, T2, T3, T4, T5, T6> action
    )
    {
        action(value1, value2, value3, value4, value5, value6);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5, T6, T7>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7,
        Action<T1, T2, T3, T4, T5, T6, T7> action
    )
    {
        action(value1, value2, value3, value4, value5, value6, value7);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5, T6, T7, T8>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7,
        T8 value8,
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action
    )
    {
        action(value1, value2, value3, value4, value5, value6, value7, value8);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2>(
        (T1, T2) value,
        Action<T1, T2> action
    )
    {
        action(value.Item1, value.Item2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3>(
        (T1, T2, T3) value,
        Action<T1, T2, T3> action
    )
    {
        action(value.Item1, value.Item2, value.Item3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4>(
        (T1, T2, T3, T4) value,
        Action<T1, T2, T3, T4> action
    )
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5>(
        (T1, T2, T3, T4, T5) value,
        Action<T1, T2, T3, T4, T5> action
    )
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5, T6>(
        (T1, T2, T3, T4, T5, T6) value,
        Action<T1, T2, T3, T4, T5, T6> action
    )
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5, T6, T7>(
        (T1, T2, T3, T4, T5, T6, T7) value,
        Action<T1, T2, T3, T4, T5, T6, T7> action
    )
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void Run<T1, T2, T3, T4, T5, T6, T7, T8>(
        (T1, T2, T3, T4, T5, T6, T7, T8) value,
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action
    )
    {
        action(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7, value.Item8);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, TResult>(
        T1 value1,
        T2 value2,
        Func<T1, T2, TResult> fn
    )
    {
        return fn(value1, value2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, TResult>(
        T1 value1,
        T2 value2,
        T3 value3,
        Func<T1, T2, T3, TResult> fn
    )
    {
        return fn(value1, value2, value3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, TResult>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        Func<T1, T2, T3, T4, TResult> fn
    )
    {
        return fn(value1, value2, value3, value4);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, TResult>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        Func<T1, T2, T3, T4, T5, TResult> fn
    )
    {
        return fn(value1, value2, value3, value4, value5);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, T6, TResult>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        Func<T1, T2, T3, T4, T5, T6, TResult> fn
    )
    {
        return fn(value1, value2, value3, value4, value5, value6);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, T6, T7, TResult>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7,
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn
    )
    {
        return fn(value1, value2, value3, value4, value5, value6, value7);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        T1 value1,
        T2 value2,
        T3 value3,
        T4 value4,
        T5 value5,
        T6 value6,
        T7 value7,
        T8 value8,
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn
    )
    {
        return fn(value1, value2, value3, value4, value5, value6, value7, value8);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, TResult>(
        (T1, T2) value,
        Func<T1, T2, TResult> fn
    )
    {
        return fn(value.Item1, value.Item2);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, TResult>(
        (T1, T2, T3) value,
        Func<T1, T2, T3, TResult> fn
    )
    {
        return fn(value.Item1, value.Item2, value.Item3);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, TResult>(
        (T1, T2, T3, T4) value,
        Func<T1, T2, T3, T4, TResult> fn
    )
    {
        return fn(value.Item1, value.Item2, value.Item3, value.Item4);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, TResult>(
        (T1, T2, T3, T4, T5) value,
        Func<T1, T2, T3, T4, T5, TResult> fn
    )
    {
        return fn(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, T6, TResult>(
        (T1, T2, T3, T4, T5, T6) value,
        Func<T1, T2, T3, T4, T5, T6, TResult> fn
    )
    {
        return fn(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, T6, T7, TResult>(
        (T1, T2, T3, T4, T5, T6, T7) value,
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn
    )
    {
        return fn(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static TResult Run<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        (T1, T2, T3, T4, T5, T6, T7, T8) value,
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn
    )
    {
        return fn(value.Item1, value.Item2, value.Item3, value.Item4, value.Item5, value.Item6, value.Item7, value.Item8);
    }
}
