// <auto-generated />
namespace Macaron.Functional;

partial class Utility
{
    public static Action<T2, T1> Flip<T1, T2>(
        Action<T1, T2> action
    )
    {
        return (arg1,  arg2) => action(arg2, arg1);
    }

    public static Func<T2, T1, TResult> Flip<T1, T2, TResult>(
        Func<T1, T2, TResult> fn
    )
    {
        return (arg1,  arg2) => fn(arg2, arg1);
    }

    public static Action<T2, T1, T3> Flip<T1, T2, T3>(
        Action<T1, T2, T3> action
    )
    {
        return (arg1, arg2,  arg3) => action(arg2, arg1, arg3);
    }

    public static Func<T2, T1, T3, TResult> Flip<T1, T2, T3, TResult>(
        Func<T1, T2, T3, TResult> fn
    )
    {
        return (arg1, arg2,  arg3) => fn(arg2, arg1, arg3);
    }

    public static Action<T2, T1, T3, T4> Flip<T1, T2, T3, T4>(
        Action<T1, T2, T3, T4> action
    )
    {
        return (arg1, arg2, arg3,  arg4) => action(arg2, arg1, arg3, arg4);
    }

    public static Func<T2, T1, T3, T4, TResult> Flip<T1, T2, T3, T4, TResult>(
        Func<T1, T2, T3, T4, TResult> fn
    )
    {
        return (arg1, arg2, arg3,  arg4) => fn(arg2, arg1, arg3, arg4);
    }

    public static Action<T2, T1, T3, T4, T5> Flip<T1, T2, T3, T4, T5>(
        Action<T1, T2, T3, T4, T5> action
    )
    {
        return (arg1, arg2, arg3, arg4,  arg5) => action(arg2, arg1, arg3, arg4, arg5);
    }

    public static Func<T2, T1, T3, T4, T5, TResult> Flip<T1, T2, T3, T4, T5, TResult>(
        Func<T1, T2, T3, T4, T5, TResult> fn
    )
    {
        return (arg1, arg2, arg3, arg4,  arg5) => fn(arg2, arg1, arg3, arg4, arg5);
    }

    public static Action<T2, T1, T3, T4, T5, T6> Flip<T1, T2, T3, T4, T5, T6>(
        Action<T1, T2, T3, T4, T5, T6> action
    )
    {
        return (arg1, arg2, arg3, arg4, arg5,  arg6) => action(arg2, arg1, arg3, arg4, arg5, arg6);
    }

    public static Func<T2, T1, T3, T4, T5, T6, TResult> Flip<T1, T2, T3, T4, T5, T6, TResult>(
        Func<T1, T2, T3, T4, T5, T6, TResult> fn
    )
    {
        return (arg1, arg2, arg3, arg4, arg5,  arg6) => fn(arg2, arg1, arg3, arg4, arg5, arg6);
    }

    public static Action<T2, T1, T3, T4, T5, T6, T7> Flip<T1, T2, T3, T4, T5, T6, T7>(
        Action<T1, T2, T3, T4, T5, T6, T7> action
    )
    {
        return (arg1, arg2, arg3, arg4, arg5, arg6,  arg7) => action(arg2, arg1, arg3, arg4, arg5, arg6, arg7);
    }

    public static Func<T2, T1, T3, T4, T5, T6, T7, TResult> Flip<T1, T2, T3, T4, T5, T6, T7, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> fn
    )
    {
        return (arg1, arg2, arg3, arg4, arg5, arg6,  arg7) => fn(arg2, arg1, arg3, arg4, arg5, arg6, arg7);
    }

    public static Action<T2, T1, T3, T4, T5, T6, T7, T8> Flip<T1, T2, T3, T4, T5, T6, T7, T8>(
        Action<T1, T2, T3, T4, T5, T6, T7, T8> action
    )
    {
        return (arg1, arg2, arg3, arg4, arg5, arg6, arg7,  arg8) => action(arg2, arg1, arg3, arg4, arg5, arg6, arg7, arg8);
    }

    public static Func<T2, T1, T3, T4, T5, T6, T7, T8, TResult> Flip<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> fn
    )
    {
        return (arg1, arg2, arg3, arg4, arg5, arg6, arg7,  arg8) => fn(arg2, arg1, arg3, arg4, arg5, arg6, arg7, arg8);
    }

}
