// <auto-generated />
namespace Macaron.Functional;

partial class Utility
{
    public static T1 Item1<T1, T2>((T1, T2) tuple)
    {
        return tuple.Item1;
    }

    public static T2 Item2<T1, T2>((T1, T2) tuple)
    {
        return tuple.Item2;
    }

    public static T1 Item1<T1, T2, T3>((T1, T2, T3) tuple)
    {
        return tuple.Item1;
    }

    public static T2 Item2<T1, T2, T3>((T1, T2, T3) tuple)
    {
        return tuple.Item2;
    }

    public static T3 Item3<T1, T2, T3>((T1, T2, T3) tuple)
    {
        return tuple.Item3;
    }

    public static T1 Item1<T1, T2, T3, T4>((T1, T2, T3, T4) tuple)
    {
        return tuple.Item1;
    }

    public static T2 Item2<T1, T2, T3, T4>((T1, T2, T3, T4) tuple)
    {
        return tuple.Item2;
    }

    public static T3 Item3<T1, T2, T3, T4>((T1, T2, T3, T4) tuple)
    {
        return tuple.Item3;
    }

    public static T4 Item4<T1, T2, T3, T4>((T1, T2, T3, T4) tuple)
    {
        return tuple.Item4;
    }

    public static T1 Item1<T1, T2, T3, T4, T5>((T1, T2, T3, T4, T5) tuple)
    {
        return tuple.Item1;
    }

    public static T2 Item2<T1, T2, T3, T4, T5>((T1, T2, T3, T4, T5) tuple)
    {
        return tuple.Item2;
    }

    public static T3 Item3<T1, T2, T3, T4, T5>((T1, T2, T3, T4, T5) tuple)
    {
        return tuple.Item3;
    }

    public static T4 Item4<T1, T2, T3, T4, T5>((T1, T2, T3, T4, T5) tuple)
    {
        return tuple.Item4;
    }

    public static T5 Item5<T1, T2, T3, T4, T5>((T1, T2, T3, T4, T5) tuple)
    {
        return tuple.Item5;
    }

    public static T1 Item1<T1, T2, T3, T4, T5, T6>((T1, T2, T3, T4, T5, T6) tuple)
    {
        return tuple.Item1;
    }

    public static T2 Item2<T1, T2, T3, T4, T5, T6>((T1, T2, T3, T4, T5, T6) tuple)
    {
        return tuple.Item2;
    }

    public static T3 Item3<T1, T2, T3, T4, T5, T6>((T1, T2, T3, T4, T5, T6) tuple)
    {
        return tuple.Item3;
    }

    public static T4 Item4<T1, T2, T3, T4, T5, T6>((T1, T2, T3, T4, T5, T6) tuple)
    {
        return tuple.Item4;
    }

    public static T5 Item5<T1, T2, T3, T4, T5, T6>((T1, T2, T3, T4, T5, T6) tuple)
    {
        return tuple.Item5;
    }

    public static T6 Item6<T1, T2, T3, T4, T5, T6>((T1, T2, T3, T4, T5, T6) tuple)
    {
        return tuple.Item6;
    }

    public static T1 Item1<T1, T2, T3, T4, T5, T6, T7>((T1, T2, T3, T4, T5, T6, T7) tuple)
    {
        return tuple.Item1;
    }

    public static T2 Item2<T1, T2, T3, T4, T5, T6, T7>((T1, T2, T3, T4, T5, T6, T7) tuple)
    {
        return tuple.Item2;
    }

    public static T3 Item3<T1, T2, T3, T4, T5, T6, T7>((T1, T2, T3, T4, T5, T6, T7) tuple)
    {
        return tuple.Item3;
    }

    public static T4 Item4<T1, T2, T3, T4, T5, T6, T7>((T1, T2, T3, T4, T5, T6, T7) tuple)
    {
        return tuple.Item4;
    }

    public static T5 Item5<T1, T2, T3, T4, T5, T6, T7>((T1, T2, T3, T4, T5, T6, T7) tuple)
    {
        return tuple.Item5;
    }

    public static T6 Item6<T1, T2, T3, T4, T5, T6, T7>((T1, T2, T3, T4, T5, T6, T7) tuple)
    {
        return tuple.Item6;
    }

    public static T7 Item7<T1, T2, T3, T4, T5, T6, T7>((T1, T2, T3, T4, T5, T6, T7) tuple)
    {
        return tuple.Item7;
    }

    public static T1 Item1<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item1;
    }

    public static T2 Item2<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item2;
    }

    public static T3 Item3<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item3;
    }

    public static T4 Item4<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item4;
    }

    public static T5 Item5<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item5;
    }

    public static T6 Item6<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item6;
    }

    public static T7 Item7<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item7;
    }

    public static T8 Item8<T1, T2, T3, T4, T5, T6, T7, T8>((T1, T2, T3, T4, T5, T6, T7, T8) tuple)
    {
        return tuple.Item8;
    }

}
