// <auto-generated />
namespace Macaron.Functional;

partial class Utility
{
    public static Func<T1, T3> Compose<T1, T2, T3>(
        Func<T2, T3> fn1,
        Func<T1, T2> fn2
    )
    {
        return value =>
        {
            var result1 = fn2(value);
            var result2 = fn1(result1);

            return result2;
        };
    }

    public static Func<T1, T4> Compose<T1, T2, T3, T4>(
        Func<T3, T4> fn1,
        Func<T2, T3> fn2,
        Func<T1, T2> fn3
    )
    {
        return value =>
        {
            var result1 = fn3(value);
            var result2 = fn2(result1);
            var result3 = fn1(result2);

            return result3;
        };
    }

    public static Func<T1, T5> Compose<T1, T2, T3, T4, T5>(
        Func<T4, T5> fn1,
        Func<T3, T4> fn2,
        Func<T2, T3> fn3,
        Func<T1, T2> fn4
    )
    {
        return value =>
        {
            var result1 = fn4(value);
            var result2 = fn3(result1);
            var result3 = fn2(result2);
            var result4 = fn1(result3);

            return result4;
        };
    }

    public static Func<T1, T6> Compose<T1, T2, T3, T4, T5, T6>(
        Func<T5, T6> fn1,
        Func<T4, T5> fn2,
        Func<T3, T4> fn3,
        Func<T2, T3> fn4,
        Func<T1, T2> fn5
    )
    {
        return value =>
        {
            var result1 = fn5(value);
            var result2 = fn4(result1);
            var result3 = fn3(result2);
            var result4 = fn2(result3);
            var result5 = fn1(result4);

            return result5;
        };
    }

    public static Func<T1, T7> Compose<T1, T2, T3, T4, T5, T6, T7>(
        Func<T6, T7> fn1,
        Func<T5, T6> fn2,
        Func<T4, T5> fn3,
        Func<T3, T4> fn4,
        Func<T2, T3> fn5,
        Func<T1, T2> fn6
    )
    {
        return value =>
        {
            var result1 = fn6(value);
            var result2 = fn5(result1);
            var result3 = fn4(result2);
            var result4 = fn3(result3);
            var result5 = fn2(result4);
            var result6 = fn1(result5);

            return result6;
        };
    }

    public static Func<T1, T8> Compose<T1, T2, T3, T4, T5, T6, T7, T8>(
        Func<T7, T8> fn1,
        Func<T6, T7> fn2,
        Func<T5, T6> fn3,
        Func<T4, T5> fn4,
        Func<T3, T4> fn5,
        Func<T2, T3> fn6,
        Func<T1, T2> fn7
    )
    {
        return value =>
        {
            var result1 = fn7(value);
            var result2 = fn6(result1);
            var result3 = fn5(result2);
            var result4 = fn4(result3);
            var result5 = fn3(result4);
            var result6 = fn2(result5);
            var result7 = fn1(result6);

            return result7;
        };
    }

    public static Func<T1, T9> Compose<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        Func<T8, T9> fn1,
        Func<T7, T8> fn2,
        Func<T6, T7> fn3,
        Func<T5, T6> fn4,
        Func<T4, T5> fn5,
        Func<T3, T4> fn6,
        Func<T2, T3> fn7,
        Func<T1, T2> fn8
    )
    {
        return value =>
        {
            var result1 = fn8(value);
            var result2 = fn7(result1);
            var result3 = fn6(result2);
            var result4 = fn5(result3);
            var result5 = fn4(result4);
            var result6 = fn3(result5);
            var result7 = fn2(result6);
            var result8 = fn1(result7);

            return result8;
        };
    }

}
